# Generated by Django 3.1.2 on 2021-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_str',
            field=models.CharField(default='', max_length=200),
        ),
    ]
