# Generated by Django 3.1.2 on 2021-02-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_order_str'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
